# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # disable synced folder
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # configure vagrant username and pass
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  # configure metasploitable instance
  config.vm.define "metasploitable" do |instance|
    instance.vm.box = "rapid7/metasploitable3-ub1404"

    instance.vm.hostname = "metasploitable"
    instance.vm.network "private_network", ip: '172.28.128.3'

    instance.vm.provider "virtualbox" do |v|
      v.name = "metasploitable"
      v.memory = 2048
    end
  end

  # WebGoat
  config.vm.define "webgoat" do |instance|
    instance.vm.box = "owaspwebgoat/webgoat"
    instance.vm.box_version = "8.0.M26"

    instance.vm.hostname = "webgoat"
    instance.vm.network "private_network", ip: '172.28.128.4'

    instance.vm.provider :virtualbox do |v|
      v.name = "webgoat"
      v.memory = 2048
    end
  end

  # define kali instance
  config.vm.define "kali" do |instance|

    # vagrant box
    instance.vm.box = "kalilinux/rolling"

    instance.vm.hostname = "kali"
    instance.vm.network "private_network", ip: '172.28.128.10'

    # define a vm
    instance.vm.provider :virtualbox do |v|
      v.name = "kali"
      v.memory = 4096
    end

    # provision script
    instance.vm.provision "shell", inline: <<-SHELL
      apt-get update -qq
      sed -i 's/us/fi/g' /etc/default/keyboard
    SHELL
  end
end
